kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: 首次构建测试
    commands:
      - sudo mkdir ./build
      - echo "hello world"
      - sudo touch ~/hello.txt
      - who
      - mkdir hello
      - sudo systemctl status gitea.service
