kind: pipeline
type: exec
name: 基本构建流程

platform:
  os: linux
  arch: amd64

steps:
  - name: 首次构建测试
    commands:
      - pwd
      - ls -l
      - cd ~
      - ls ~
      - sudo mkdir ./build
      - ls
      - echo $HOME
      - pwd
      - hostnamectl
      - echo "hello world"
      - sudo touch ~/hello.txt
      - mkdir hello
